{{- $normalizedOs := $.chezmoi.os | replace "darwin" "macos" -}}
{{- $osTitle := $.chezmoi.os | title -}}

{{ if get .packages "external" -}}
{{- range .packages.external }}
{{ .target | quote }}:
  {{- .config | toYaml | trim | nindent 2 | replace "${os}" $normalizedOs | replace "${osTitle}" $osTitle | replace "${arch}" $.chezmoi.arch }}
{{- end }}

{{ end -}}

